### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터 빠르게 계산을 해야 한다.
- 행렬 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징 
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 선형대수학을 빠르게 연산
            - 스칼라, 벡터, 매트릭스

In [2]:
import numpy as np

In [3]:
# 행렬 데이터 생성 
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능(str은 str만 int는 int만 으로 통일)

In [ ]:
# array 모듈 (class) 내, 함수를 이용하기 위해 '객체'를 형성해야 한다 그래야 
# C언어로 작성된 numpy가 빠른(C언어로/class내 함수를 불러와) 계산이 가능하다.

In [4]:
array = np.array([1,2,3,])
type(array),array

(numpy.ndarray, array([1, 2, 3]))

In [ ]:
#  리스트만 있으면 벡터, 리스트안에 리스트가 있으면 2차행렬, 리스트안에 리스트안에 리스트가 있으면 3차행렬
#  array2.ndim, array2.shape n차행렬 확인
#  shape은 밖에서 안쪽순으로 표시 2열 리스트안의 갯수 3

In [11]:
array2 = np.array(
    [[1,2,3],
    [4,5,6]],
)
array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [14]:
# 행렬의 모양(shape) 변경하기
# reshape 안의 수 곱과 array values 전체 갯수의 수가 같아야 함
array2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [17]:
# 행렬 데이터의 선택 : offset index : masking

In [23]:
array2[1][::-1]

array([6, 5, 4])

In [26]:
array2[1,2] # ==array2[1][2]

6

In [27]:
# 데이터 수정

In [29]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [28]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array2[1][2]=10

In [31]:
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [32]:
# 브로드 캐스팅
array2[0] = 0

In [33]:
array2 

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [34]:
array2[0] =[7,8,9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [36]:
# 조건으로 선택
idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [ ]:
# 마스킹 True인 데이터만 남김(필터링)

In [37]:
array2[idx] 

array([ 8,  9, 10])

In [ ]:
#결과적으로 7보다 큰 idx는 100으로 치환된 값이 출력

In [39]:
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [41]:
 # 행렬 데이터의 생성 2

In [ ]:
# 샘플데이터 만들 때, zeros, ones 데이터를 많이 사용

In [44]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
data1 = np.ones((2,3,2))
data1

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [45]:
data.dtype

dtype('float64')

In [ ]:
# 데이터타입 변경

In [47]:
data2 = data.astype("int")
data2.dtype

dtype('int32')

In [51]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [53]:
np.arange(5,10,2)

array([5, 7, 9])

## 상관계수 ( Correlation Coefficient ) 

### Index
1. 분산
2. 공분산
3. 상관계수
4. 결정계수
5. 프리미어리그 데이터 상관계수 분석

In [56]:
import numpy as np

#### 샘플 데이터 생성

In [60]:
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])

### 2. 분산 (variance)
- 1개의 이산정도를 나타냄
- 편차제곱의 평균

#### my code

In [77]:
# variance code
idx= len(data)
sub = 0
mul = 0
resutl = 0
def variance(data):
    # 각항 - 평균
    idx = len(data)
    sub = 0
    mul = 0
    resutl = 0  



    for idx in range(len(data)):
        idx -= 1
        sub = data[idx] - avg
        mul = sub **2
        mul += mul
        
    var = mul / len(data)
        
    
    
    
   # 각항 - 평균의 제곰

   #시그마
    
    
    # 1/n
    
    
    avg = np.average(data)
    var = 0
    
    
    return var

TypeError: object of type 'int' has no len()

In [61]:
len(data1)

5

In [64]:
np.average(data)

0.0

In [67]:
data1[0]

80

In [71]:
data = variance(data1)

In [72]:
data

0

In [73]:
np.average(data1)

90.0

#### answer 

In [79]:
# variance code
def Variance(data):
    
    avg=np.average(data)
    var = 0
    for num in data:
        var += (num - avg) **2
    
    
    
    
    return var / len(data)

In [84]:
Variance(data1), Variance(data2), Variance(data1) ** 0.5, Variance(data2) ** 0.5,

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [85]:
np.var(data1),np.var(data2), np.std(data1), np.std(data2)

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

### 일반함수와 numpy 함수의 퍼포먼스 비교

In [ ]:
# 10E4 10의 4승

In [88]:
p_data1 = np.random.randint(60, 100, int(10E5))
p_data2 = np.random.randint(60, 100, int(10E5))

In [94]:
# 일반함수

In [98]:
%%time
variance(p_data1), variance(p_data2)

Wall time: 963 µs


(0, 0)

In [99]:
%%time
np.var(p_data1), np.var(p_data2)

Wall time: 29 ms


(133.10050283871598, 133.18265500990393)

### 3.공분산(covariance)
- 2개의 확률변수의 상관정도를 나타냄
- 평균 편차곱
- 방향성은 보여줄 수 있으나 강도를 나타내는데 한계가 있다.
    - 표본데이터의 크기에 따라서 값의 차이가 큰, 단점이 있다.

In [116]:
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])
np.cov(data1,data2)[0,1]

93.75

In [117]:
data3 = np.array([80,85,100,90,95])
data4 = np.array([100,90,70,90,80])
np.cov(data3,data4)[0,1]

-87.5

In [118]:
data5 = np.array([800,850,1000,900,950])
data6 = np.array([1000,900,700,900,800])
np.cov(data5,data6)[0,1]

-8750.0

### 3. 상관계수(correlation coefficient)
- 공분산의 한계를 극복하기 위해서 만들어짐
- -1 ~ 1까지의 수를 가지며 0과 가까울수록 상관도가 적음을 의미
- x의 분산과 y의 분산을 곱한 결과의 제곱근을 나눠주면 x나 y의 변화량이 클수록 0에 가까워짐
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.corrcoef.html

In [ ]:
# 0과 가까울 수록, 관련이 없다 1과 가까울수록 같이 움직인다 -1과 가까울 수록 반대로 움직인다.

In [121]:
# correlation coefficient function
np.corrcoef(data1,data2), np.corrcoef(data3, data4), np.corrcoef(data5,data6)

(array([[1.        , 0.94491118],
        [0.94491118, 1.        ]]),
 array([[ 1.        , -0.97072534],
        [-0.97072534,  1.        ]]),
 array([[ 1.        , -0.97072534],
        [-0.97072534,  1.        ]]))

### 5. 결정계수(cofficient of determination: R-squared)
- x로부터 y를 예측할 수 있는 정도
- 상관계수의 제곱 (상관계수를 양수화)
- 수치가 클수록 회기분석을 통해 예측할 수 있는 수치의 정도가 더 정확

In [122]:
np.corrcoef(data1,data2)[0,1] ** 2 

0.892857142857143

In [ ]:
# data4가 data1에 더 많은 영향을 준다.

In [124]:
np.corrcoef(data1, data4)[0,1] ** 2

0.9423076923076923

In [125]:
import pandas as pd

In [126]:
!ls datas

2014_p.csv
2014_s.csv
premierleague.csv
train.csv


In [128]:
df = pd.read_csv("datas/premierleague.csv")
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [131]:
# 득점
gf = np.array(df["gf"])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31], dtype=int64)

In [132]:
# 실점
ga = np.array(df["ga"])
ga

array([27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
       56, 68, 56], dtype=int64)

In [134]:
# 승점
points = np.array(df["points"])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31], dtype=int64)

In [142]:
data1, data2 = np.corrcoef(gf, points)[0,1] ** 2, np.corrcoef(ga, points)[0,1] ** 2
data1, data2

(0.8683266496886471, 0.757933920368845)

In [ ]:
# 소수점 자리수 제어 해서 보기.

In [143]:
round(data1, 2), round(data2, 2)

(0.87, 0.76)